Repository d3b-center/bixtools, pull requests merged in 2021-02, with the labels that each got.

#83 ☁️ get GenomeAnalysisTK from google cloud
  gatk/4.beta.1-3.5/Dockerfile
Labels: bug

#86 🔥 turn off automatic pushing
  .circleci/config.yml
  .circleci/make_config.py
Labels: bug

#85 🎉 added standalone VEP93 with MSKCC vcf2maf removed and pigz added
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  VEP/r93.7/Dockerfile
Labels: feature

#90 ✨ adds gha to keep pr template in sync
  .github/workflows/sync_pr_template.yml
Labels: feature

#89 ⭕️ publish on merge
  .circleci/config.yml
  .circleci/make_config.py
Labels: feature, help wanted

#95 💆‍♂️ swap base branch heads
  .circleci/config.yml
  .circleci/make_config.py
Labels: bug
