Repository d3b-center/bixtools, pull requests merged in 2021-04, with the labels that each got.

#105 ✨ cnvnator init
  .circleci/config.yml
  cnvnator/v0.4.1/Dockerfile
Labels: bix-dev, feature

#104 🔥 update hotspot docker
  hotspots/0.1.0/Dockerfile
Labels: bix-dev, feature

#102 🔧 update dockerfile with updated script location
  consensus-merge/1.0.0/Dockerfile
Labels: bug

#107 🔧 point at new consensus script version
  consensus-merge/1.0.0/Dockerfile
Labels: bix-dev, bug

#106 ✨ Nhj theta2 docker
  .circleci/config.yml
  THetA2/0.7.0/Dockerfile
  THetA2/0.7.1/Dockerfile
Labels: bix-dev, feature

#109 Mb update vcf2maf 1.0.3
  .circleci/config.yml
  kf_vcf2maf/v1.0.3/Dockerfile
Labels: bix-dev, feature

#108 :sparkles: create docker for loompy library
  .circleci/config.yml
  loompy/2.0.16/Dockerfile
Labels: bix-dev
