Repository d3b-center/bixtools, pull requests merged in 2023-03, with the labels that each got.

#155 🐛 octopus docker fix and cleanup
  octopus/0.6.3-beta/Dockerfile
Labels: bug, bix-dev

#156 🐛 optparse now installs
  sequenza/3.0.0/Dockerfile
Labels: bug, bix-dev

#157 🐎 update htslib;
  octopus/0.6.3-beta/Dockerfile
Labels: bug, feature, bix-dev

#159 🎉 Created hisat2 docker
  .circleci/config.yml
  hisat2/2.2.1/Dockerfile
Labels: feature, bix-dev

#160 Add samtools to loh
  .circleci/config.yml
  LOH/1.0.1/Dockerfile
Labels: bix-dev

#161 Immune deconvolution docker
  .circleci/config.yml
  toolkit_immune_deconvolution/1.0.0/Dockerfile
Labels: bix-dev

#162 add seqkit dockerfile
  .circleci/config.yml
  seqkit/2.3.1/Dockerfile
  stranded/1.0.0/Dockerfile
Labels: feature, bix-dev, bix-ops
