Repository d3b-center/bixtools, pull requests merged in 2023-10, with the labels that each got.

#203 🎉 add echtvar 0.1.9
  echtvar/0.1.9/Dockerfile
Labels: feature, bix-dev

#204 Add matplotlib
  tumor-only-benchmarking/1.0.0/Dockerfile
Labels: bix-dev

#205 Add permissions for github actions
  .github/workflows/update_readme_dockers.yml
Labels: bug
