Repository d3b-center/bixtools, pull requests merged in 2023-02, with the labels that each got.

#145 Add TMB Docker
  .circleci/config.yml
  toolkit_tmb/1.0.0/Dockerfile
Labels: bix-dev

#144 Add bam readcount to loh docker
  LOH/1.0.0/Dockerfile
Labels: bix-dev

#153 🎉 annoFuse 0.92.0
  .circleci/config.yml
  annoFuse/0.92.0/Dockerfile
Labels: bug, bix-dev

#146 🎉 lancet 1.1.x docker for canine
  .circleci/config.yml
  lancet/1.1.x/Dockerfile
Labels: feature, bix-dev

#147 🐙 octopus docker for canine
  .circleci/config.yml
  octopus/0.6.3-beta/Dockerfile
Labels: feature, bix-dev

#152 🎉 msisensor docker for canine
  .circleci/config.yml
  msisensor/1.1.a/Dockerfile
Labels: feature, bix-dev

#154 🎉 add snpeff docker for canine
  .circleci/config.yml
  snpEff/4.3t/Dockerfile
Labels: feature, bix-dev

#151 🎉 new vardict for canine
  .circleci/config.yml
  VarDictJava/1.7.0/Dockerfile
Labels: feature, bix-dev

#150 🎉 sequenza 3.0.0 init
  .circleci/config.yml
  sequenza/3.0.0/Dockerfile
Labels: feature, bix-dev

#148 🎉 python util docker for canine
  .circleci/config.yml
  python/3.9-canine-util/Dockerfile
Labels: feature, bix-dev

#149 🎉 catchall tidyverse docker for canine
  .circleci/config.yml
  tidyverse/3.6.1-canine-util/Dockerfile
Labels: feature, bix-dev
